# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe108fd55b92ce60f450512b6984bfc926b15b090faafdc5519243711bd1795fcd97daeefe3947be5f28bcfe906ed3542637dba2b615d4f871e34eeee77404e4

test:
  secret_key_base: 453e07fb777637573af25d2ef8db74b7c60d6558bbf3748edc6a4a476f1d6a6708bd0d940fd9ddedda0e02863ed0c258b033b182cd4e6f5ab359621e1327007c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
